server:
  port: 7081

spring:
  application:
    name: trace-1
  sleuth:
    sampler:
      percentage: 0.8
  zipkin:
    base-url: http://127.0.0.1:9411

eureka:
  client:
    service-url:
      defaultZone: http://qoocar:qoocar@localhost:8761/eureka