server:
  port: 7082

spring:
  application:
    name: trace-2
  sleuth:
    sampler:
      percentage: 0.5
  zipkin:
    base-url: http://127.0.0.1:9411
    
eureka:
  client:
    service-url:
      defaultZone: http://qoocar:qoocar@localhost:8761/eureka