spring:
  application:
    name: ag-eureka


server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

security:
  basic:
    enabled:  false
  user:
    name: qoocar
    password: qoocar