---
spring:
    application:
        name: ag-eureka
    profiles: dev
server:
    port: 8761 #启动端口

eureka:
    client:
        registerWithEureka: false  #false:不作为一个客户端注册到注册中心
        fetchRegistry: false      #为true时，可以启动，但报异常：Cannot execute request on any known server
    server:
        enable-self-preservation: false
        eviction-interval-timer-in-ms: 10000

security:
  basic:
    enabled:  false

---
spring:
    application:
        name: ag-eureka
    profiles: test
server:
    port: 8761 #启动端口

eureka:
    client:
        registerWithEureka: false  #false:不作为一个客户端注册到注册中心
        fetchRegistry: false      #为true时，可以启动，但报异常：Cannot execute request on any known server
    server:
        enable-self-preservation: false
        eviction-interval-timer-in-ms: 10000

security:
  basic:
    enabled:  false

---
spring:
    application:
        name: ag-eureka
    profiles: peer1

server:
    port: 8761 #启动端口


eureka:
    instance:
        hostname: eureka-server-peer1
    client:
        registerWithEureka: false #false:不作为一个客户端注册到注册中心
        fetchRegistry: false      #为true时，可以启动，但报异常：Cannot execute request on any known server
        serviceUrl:
          defaultZone: http://qoocar:qoocar123@eureka-server-peer2:8762/eureka/,http://qoocar:qoocar123@eureka-server-peer3:8763/eureka/
    server:
        enable-self-preservation: false
        eviction-interval-timer-in-ms: 10000

security:
    basic:
      enabled:  true
    user:
      name: qoocar
      password: qoocar

---
spring:
    application:
        name: ag-eureka
    profiles: peer2

server:
    port: 8762 #启动端口

eureka:
    instance:
        hostname: eureka-server-peer2
    client:
        registerWithEureka: false  #false:不作为一个客户端注册到注册中心
        fetchRegistry: false      #为true时，可以启动，但报异常：Cannot execute request on any known server
        serviceUrl:
          defaultZone: http://qoocar:qoocar123@eureka-server-peer1:8761/eureka/,http://qoocar:qoocar123@eureka-server-peer3:8763/eureka/
    server:
        enable-self-preservation: false
        eviction-interval-timer-in-ms: 10000

security:
    basic:
      enabled:  true
    user:
      name: qoocar
      password: qoocar

---
spring:
    application:
        name: ag-eureka
    profiles: peer3
server:
    port: 8763 #启动端口

eureka:
    instance:
        hostname: eureka-server-peer3
    client:
        registerWithEureka: false  #false:不作为一个客户端注册到注册中心
        fetchRegistry: false      #为true时，可以启动，但报异常：Cannot execute request on any known server
        serviceUrl:
          defaultZone: http://qoocar:qoocar123@eureka-server-peer1:8761/eureka/,http://qoocar:qoocar123@eureka-server-peer2:8762/eureka/
    server:
        enable-self-preservation: false
        eviction-interval-timer-in-ms: 10000

security:
    basic:
      enabled:  true
    user:
      name: qoocar
      password: qoocar