spring:
  application:
    name: ag-auth
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/ag_gate?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20


eureka:
  client:
    service-url:
      defaultZone: http://qoocar:qoocar@localhost:8761/eureka

server:
  port: 7777

mybatis:
  basepackage: com.github.yanbin.gate.mapper
  xmlLocation: classpath:mapper/**/*.xml

jwt:
  expire: 3600
  pri-key:
    path: D:\a\ag-parent\ag-auth\src\main\resources\jwt\pri.key
  pub-key:
    path: D:\a\ag-parent\ag-auth\src\main\resources\jwt\pub.key

client:
  expire: 3600
  pri-key:
    path: D:\a\ag-parent\ag-auth\src\main\resources\client\pri.key
  pub-key:
    path: D:\a\ag-parent\ag-auth\src\main\resources\client\pub.key